### ISSUE TITLE
File or stream is not seekable

### ISSUE THREAD

**Issue by eirikr88** [tomstokes/python-spi#7]
Hi,

I'm running your code from a Raspberry Pi 3 Model B where it runs just fine under sudo rights, but without I get the following error:
```
Python 3.5.3 (default, Feb 20 2017, 12:20:42)
[GCC 4.9.2] on linux
>>> from spi import *
>>> spi = SPI("/dev/spidev0.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/venv/lib/python3.5/site-packages/spi.py", line 137, in __init__
    self.handle = open(device, "w+")
io.UnsupportedOperation: File or stream is not seekable.
```

If you have any tips that would be great, I've added my user to the spi group that has write access to the device (spidev0.0). Thanks!

**Comment by cowratt** [comment]
https://github.com/dunkelstern/python-spi/commit/6cc68dc97a4f9ee891cad35121e1ce09e9065434
